name = "Technically Optimized"
author = "Looney"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "810632c7aadcfed01265609d3126f89e3f08af8f6152675014778df76d2eb972"

[versions]
fabric = "0.15.6"
minecraft = "1.20.2"
