name = "Technically Optimized"
author = "Looney"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cae59fbd04f5019386a15b57995d164eae5c3584b70e0d9a27c7d8b0458fca8"

[versions]
fabric = "0.15.6"
minecraft = "1.20.2"
