name = "Technically Optimized"
author = "Looney"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1e9197a0d86b7b37e05484513d364d063ab9f5af3e7ea48075e9678accbd2b0"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
