name = "Technically Optimized"
author = "Looney"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f231bb077e6f136e08c5259480b175575d1d2e28e880e0f5323fc8d24094365"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
