name = "Technically Optimized"
author = "Looney"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90972312ae43039682582b684b21873828b6c40eb67bc5fd283553801ceef4da"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
