name = "Technically Optimized"
author = "Looney"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85e23ef1bc17298264747f64c58027e4916c55d9ad440870993e21ad8226c058"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
