name = "Technically Optimized"
author = "Looney"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "045514418a86dda8e446abdca4c11ec5cc96de08cb7d9c50cfe582fcb9608871"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
