name = "Technically Optimized"
author = "Looney"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51ed44f76725c103060287ea4a507333d994571aa783cb2a0d9f180546b98a61"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
