name = "Technically Optimized"
author = "Looney"
version = "3.0.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5aa0fe4ff4599b9199fe4460a05904fbf381dc34b6774dbc5e64ca09c917719c"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
